FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY src/dashboard /app/src/dashboard

# Expose Streamlit port
EXPOSE 8501

# Set Streamlit healthcheck and start command
ENV PYTHONPATH=/app
CMD ["streamlit", "run", "src/dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
